[2024-01-18T11:56:28.249+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_bipo_dag.call_api_and_process manual__2024-01-18T11:56:23.682758+00:00 [queued]>
[2024-01-18T11:56:28.265+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_bipo_dag.call_api_and_process manual__2024-01-18T11:56:23.682758+00:00 [queued]>
[2024-01-18T11:56:28.265+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-18T11:56:28.283+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): call_api_and_process> on 2024-01-18 11:56:23.682758+00:00
[2024-01-18T11:56:28.291+0000] {standard_task_runner.py:60} INFO - Started process 1279 to run task
[2024-01-18T11:56:28.295+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'my_bipo_dag', 'call_api_and_process', 'manual__2024-01-18T11:56:23.682758+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/bipo_employee_info.py', '--cfg-path', '/tmp/tmp685kcaxx']
[2024-01-18T11:56:28.297+0000] {standard_task_runner.py:88} INFO - Job 53: Subtask call_api_and_process
[2024-01-18T11:56:28.316+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-01-18T11:56:28.362+0000] {task_command.py:423} INFO - Running <TaskInstance: my_bipo_dag.call_api_and_process manual__2024-01-18T11:56:23.682758+00:00 [running]> on host 602769a70f45
[2024-01-18T11:56:28.613+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_bipo_dag' AIRFLOW_CTX_TASK_ID='call_api_and_process' AIRFLOW_CTX_EXECUTION_DATE='2024-01-18T11:56:23.682758+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-18T11:56:23.682758+00:00'
[2024-01-18T11:56:58.635+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-01-18T11:56:58.639+0000] {process_utils.py:131} INFO - Sending 15 to group 1279. PIDs of all processes in the group: [1279]
[2024-01-18T11:56:58.640+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1279
[2024-01-18T11:56:58.640+0000] {taskinstance.py:2451} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-01-18T11:56:58.693+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1279, status='terminated', exitcode=0, started='11:56:28') (1279) terminated with exit code 0
