[2023-12-12T09:07:03.468+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bipo_dag_emp_info.transform_response scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-12-12T09:07:03.480+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bipo_dag_emp_info.transform_response scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-12-12T09:07:03.481+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-12T09:07:03.496+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform_response> on 2023-01-06 00:00:00+00:00
[2023-12-12T09:07:03.502+0000] {standard_task_runner.py:57} INFO - Started process 1324 to run task
[2023-12-12T09:07:03.504+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bipo_dag_emp_info', 'transform_response', 'scheduled__2023-01-06T00:00:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/bipo_employee_info.py', '--cfg-path', '/tmp/tmpi4bx63o_']
[2023-12-12T09:07:03.507+0000] {standard_task_runner.py:85} INFO - Job 102: Subtask transform_response
[2023-12-12T09:07:03.523+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-12-12T09:07:03.566+0000] {task_command.py:416} INFO - Running <TaskInstance: bipo_dag_emp_info.transform_response scheduled__2023-01-06T00:00:00+00:00 [running]> on host e1a26a98da8f
[2023-12-12T09:07:03.645+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bipo_dag_emp_info' AIRFLOW_CTX_TASK_ID='transform_response' AIRFLOW_CTX_EXECUTION_DATE='2023-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-06T00:00:00+00:00'
[2023-12-12T09:07:03.657+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bipo_employee_info.py", line 33, in transform_response
    if response.status_code == 200:
AttributeError: 'NoneType' object has no attribute 'status_code'
[2023-12-12T09:07:03.671+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bipo_dag_emp_info, task_id=transform_response, execution_date=20230106T000000, start_date=20231212T090703, end_date=20231212T090703
[2023-12-12T09:07:03.683+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 102 for task transform_response ('NoneType' object has no attribute 'status_code'; 1324)
[2023-12-12T09:07:03.717+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-12T09:07:03.736+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
