[2023-12-12T09:07:14.314+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bipo_dag_emp_info.transform_response scheduled__2023-01-26T00:00:00+00:00 [queued]>
[2023-12-12T09:07:14.326+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bipo_dag_emp_info.transform_response scheduled__2023-01-26T00:00:00+00:00 [queued]>
[2023-12-12T09:07:14.327+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-12T09:07:14.342+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform_response> on 2023-01-26 00:00:00+00:00
[2023-12-12T09:07:14.348+0000] {standard_task_runner.py:57} INFO - Started process 1504 to run task
[2023-12-12T09:07:14.354+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bipo_dag_emp_info', 'transform_response', 'scheduled__2023-01-26T00:00:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/bipo_employee_info.py', '--cfg-path', '/tmp/tmpzngc690a']
[2023-12-12T09:07:14.367+0000] {standard_task_runner.py:85} INFO - Job 155: Subtask transform_response
[2023-12-12T09:07:14.393+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-12-12T09:07:14.441+0000] {task_command.py:416} INFO - Running <TaskInstance: bipo_dag_emp_info.transform_response scheduled__2023-01-26T00:00:00+00:00 [running]> on host e1a26a98da8f
[2023-12-12T09:07:14.538+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bipo_dag_emp_info' AIRFLOW_CTX_TASK_ID='transform_response' AIRFLOW_CTX_EXECUTION_DATE='2023-01-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-26T00:00:00+00:00'
[2023-12-12T09:07:14.552+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bipo_employee_info.py", line 33, in transform_response
    if response.status_code == 200:
AttributeError: 'NoneType' object has no attribute 'status_code'
[2023-12-12T09:07:14.567+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=bipo_dag_emp_info, task_id=transform_response, execution_date=20230126T000000, start_date=20231212T090714, end_date=20231212T090714
[2023-12-12T09:07:14.581+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 155 for task transform_response ('NoneType' object has no attribute 'status_code'; 1504)
[2023-12-12T09:07:14.661+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-12T09:07:14.747+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
